### ISSUE TITLE
Major Refactor

### ISSUE THREAD

**Issue by TheGrimSilence** [TheGrimSilence/Yarn-2-Webpack-TypeScript#2]
## TODO
- Bugs
  - [x] Fix Webpack hanging
- Maintenance
  - [ ] ~~Implement `webpack-dev-server` and related react tooling~~
  - [ ] Get `frontend` connected to `services`
  - [x] Make the demo page pretty
  - [x] Isolate and `webpack-merge` specific webpack configs (frontend, services, config)
    - [x] `frontend.config.ts` - builds the frontend app and server
    - [x] `services.config.ts` - builds the services
    - [x] `main.config.ts` - controls optimizations and environment-based builds
- Implementations
  - [ ] ~~Get Started with Apollo GraphQL and Apollo Federation~~
  - [ ] ~~Create Dockerfile and integrate K8s~~

**Comment by TheGrimSilence** [comment]
Notable Finding(s):
- `cross-env` doesn't work with Yarn 2, but Yarn's new interpreter does the job for you anyway!
  - See "Normalized Shell" in [this blog](https://dev.to/arcanis/introducing-yarn-2-4eh1).

**Comment by TheGrimSilence** [comment]
In the future, `react-hot-loader` may be supported, however since ts-loader must be replaced with babel, and I *__HATE__* babel, I'll consider waiting for `react-fast-refresh` to support webpack.
